# [manager]
# prepend_keymap = [
#     { on = "q", run = "close", desc = "Close current tab" },
#     { on = "Q", run = "quit", desc = "Quit yazi"},
# ]

[[mgr.prepend_keymap]]
on = "q"
run = "close"
desc = "Close current tab"

[[mgr.prepend_keymap]]
on = "Q"
run = "quit"
desc = "Quit yazi"
