[manager]
ratio = [1, 2, 4]
linemode = "size_and_mtime"

[preview]
max_width = 2000
max_height = 2000
image_quality = 80

[opener]
play = [
    { run = 'mpv --force-window %s', orphan = true, for = "unix" },
]

pdf_viewer = [
    { run = 'zathura %s', orphan = true, for = "unix" },
]

image_external = [
    { run = 'sxiv -g 1440x980 -s w %s', orphan = true, for = "unix" },
]

ms_office = [
    { run = '''for f in "$@"; do cmd.exe /C start "" "$(wslpath -w "$f")"; done''', orphan = true, for = "unix" },
]


edit = [
    { run = '$EDITOR %s', block = true, for = "unix" },
]

[open]
prepend_rules = [
    { mime = "application/vnd.openxmlformats-officedocument.*", use = "ms_office" },
    { mime = "application/vnd.ms-{word,excel,powerpoint}", use = "ms_office" },
    { url = "*.{doc,docx,xls,xlsx,ppt,pptx}", use = "ms_office" },
    { mime = "image/*", use = [ "image_external" ] },
    { mime = "application/{pdf,epub}", use = "pdf_viewer" },
    { url = "*.js", use = "edit" },
    { url = "*.html", use = ["edit", "open", "reveal"] },
    { mime = "image/*", use = [ "image_viewer", "reveal" ] },
    { mime = "{audio,video}/*", use = [ "play", "reveal" ] },
]

[plugin]
prepend_previewers = [
    { mime = "text/csv", run = "duckdb" },
    { mime = "application/csv", run = "duckdb" },
    { url = "*.csv", run = "duckdb" },
    { url = "*.tsv", run = "duckdb" },
    { url = "*.parquet", run = "duckdb" },
    { url = "*.json", run = "duckdb" },
    { url = "*.duckdb", run = "duckdb" },
    { url = "*.db", run = "duckdb" },

    { mime = "{image,audio,video}/*", run = "mediainfo" },
    { mime = "application/x-subrip", run = "mediainfo" },
    { mime = "application/{*zip,tar,bzip2,7z*,rar,xz,zstd,java-archive}", run  = "ouch" },
    { url = "*.md", run = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"' },
]

prepend_preloaders = [
    { url = "*.csv", run = "duckdb", multi = false },
    { url = "*.tsv", run = "duckdb", multi = false },
    { url = "*.json", run = "duckdb", multi = false },
    { url = "*.parquet", run = "duckdb", multi = false },
    { url = "*.avro", run = "duckdb", multi = false },
    { url = "*.txt", run = "duckdb", multi = false },
    { url = "*.xlsx", run = "duckdb", multi = false },
]
